buildType:
  default: debug
  description: Build option
  choices:
    debug:
      short: Debug
      long: Build with debugging information
      buildType: Debug
    release:
      short: Release
      long: Releaed build
      buildType: Release
